# Generated by Django 2.1 on 2019-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
    ]
